### ISSUE TITLE
not work export.exe

### ISSUE THREAD

**Issue by kroamele1232** [MrStPL-codes/CatherineBmdExport#1]
i tried to export the files, but they're not working.

**Comment by MrStPL-codes** [comment]
> i tried to export the files, but they're not working.
Which file? Which version of the game?

**Comment by kroamele1232** [comment]
event e001 010 m000.bmd and charselect.bmd latest version steam

**Comment by MrStPL-codes** [comment]
I don't have the latest version of catherine, but I'll try to get it and fix it.

**Comment by MrStPL-codes** [comment]
I bought this game on Steam and checked if it works. Everything is fine for me and it works without any problems. Are you sure you are using the tool correctly? In the folder with the utility, place the file and enable CMD and enter "catherineBmdExport.exe m000.bmd".

**Comment by kroamele1232** [comment]
oh my bad sorry i didn't know we had to open cmd .

when does the import feature coming?

**Comment by MrStPL-codes** [comment]
I'm not sure, but I'll try to finish by the end of the month.

**Comment by kroamele1232** [comment]
hey dude what happened to the import tool ?
